-- Create the database tables

CREATE TABLE staging_table (
    customer_id INT,
    age INT,
    gender VARCHAR2(10),
    loyalty_member VARCHAR2(3),
    product_id VARCHAR2(20),
    product_type VARCHAR2(25),
    unit_price NUMBER(7,2),
    rating INT NOT NULL,
    quantity INT,
    total_price NUMBER(10,2),
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    order_status VARCHAR2(20),
    payment_method VARCHAR2(20),
    purchase_date DATE,
    shipping_type VARCHAR2(20),
    add_ons_purchased VARCHAR2(255),
    add_on_total NUMBER(10,2)
);

CREATE TABLE customer (
    customer_id INT PRIMARY KEY,
    age INT,
    gender VARCHAR2(10)
);

CREATE TABLE product (
    product_id VARCHAR2(20) PRIMARY KEY,
    product_type VARCHAR2(25),
    unit_price NUMBER(7,2)
);

CREATE TABLE orders (
    order_id NUMBER PRIMARY KEY,
    customer_id INT,
    product_id VARCHAR2(20),
    quantity INT,
    total_price NUMBER(10,2),
    order_status VARCHAR2(20),
    payment_method VARCHAR2(20),
    purchase_date DATE,
    loyalty_member VARCHAR2(3),
    rating INT NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES customer(customer_id),
    FOREIGN KEY (product_id) REFERENCES product(product_id)
);

CREATE TABLE shipping (
    order_id NUMBER PRIMARY KEY,
    shipping_type VARCHAR2(20),
    FOREIGN KEY (order_id) REFERENCES orders(order_id)
);

CREATE TABLE add_ons (
    order_id NUMBER PRIMARY KEY,
    add_ons_purchased VARCHAR2(255),
    add_on_total NUMBER(10,2),
    FOREIGN KEY (order_id) REFERENCES orders(order_id)
);

CREATE TABLE staging_table_backup AS
SELECT * FROM staging_table;

-- Populate the customer table
INSERT INTO customer (customer_id, age, gender)
SELECT DISTINCT customer_id, age, gender
FROM staging_table;

-- Populate the product table
INSERT INTO product (product_id, product_type, unit_price)
SELECT DISTINCT product_id, product_type, unit_price 
FROM staging_table;

-- Populate the orders table
INSERT INTO orders (
    order_id,
    customer_id,
    product_id,
    quantity,
    total_price,
    order_status,
    payment_method,
    purchase_date,
    loyalty_member,
    rating
)
SELECT
    order_id,
    customer_id,
    product_id,
    quantity,
    total_price,
    order_status,
    payment_method,
    purchase_date,
    loyalty_member,
    rating
FROM staging_table;

-- Populate the shipping table
INSERT INTO shipping (order_id, shipping_type)
SELECT order_id, shipping_type
FROM staging_table;

-- Populate the add_ons table
INSERT INTO add_ons (order_id, add_ons_purchased, add_on_total)
SELECT order_id, add_ons_purchased, add_on_total
FROM staging_table;
