--ANALYSIS

--calculate running total of each customer
SELECT CUSTOMER_ID, PURCHASE_DATE, TOTAL_PRICE,
    SUM(TOTAL_PRICE) OVER (PARTITION BY CUSTOMER_ID ORDER BY PURCHASE_DATE) AS RUNNING_TOTAL
FROM ORDERS;

--calculate running total of all orders
SELECT ORDER_ID, PURCHASE_DATE, TOTAL_PRICE,
    SUM(TOTAL_PRICE) OVER (ORDER BY PURCHASE_DATE, ORDER_ID) AS RUNNING_TOTAL
FROM ORDERS;

--rank customer by the most spending for given product type
SELECT PRODUCT_TYPE, CUSTOMER_ID, TOTAL_SPENDING,
    RANK() OVER (PARTITION BY PRODUCT_TYPE ORDER BY TOTAL_SPENDING DESC) AS CUST_RANK
FROM (
    SELECT P.PRODUCT_TYPE, O.CUSTOMER_ID, SUM(O.TOTAL_PRICE) AS TOTAL_SPENDING
    FROM PRODUCT P
    JOIN ORDERS O
    ON P.PRODUCT_ID = O.PRODUCT_ID
    GROUP BY P.PRODUCT_TYPE, O.CUSTOMER_ID
) 
ORDER BY PRODUCT_TYPE, CUST_RANK;

--rank products by average rating
WITH PRODUCT_ORDERS AS (
    SELECT P.PRODUCT_TYPE, P.PRODUCT_ID, O.RATING
    FROM PRODUCT P
    JOIN ORDERS O
    ON P.PRODUCT_ID = O.PRODUCT_ID
)
SELECT PRODUCT_TYPE, PRODUCT_ID,
    RANK() OVER (ORDER BY AVG(RATING) DESC) AS PRODUCT_RANK,
    AVG(RATING) AS AVG_RATING
FROM PRODUCT_ORDERS
GROUP BY PRODUCT_TYPE, PRODUCT_ID;

-- Does gender influence product type
WITH ORDER_PRODUCT AS (
SELECT C.CUSTOMER_ID, C.GENDER, O.PRODUCT_ID
FROM CUSTOMER C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
) 
SELECT P.PRODUCT_TYPE, OP.GENDER, COUNT(P.PRODUCT_TYPE) AS P_GEND_COUNT
FROM ORDER_PRODUCT OP
JOIN PRODUCT P
ON OP.PRODUCT_ID = P.PRODUCT_ID
GROUP BY OP.GENDER, P.PRODUCT_TYPE
ORDER BY P.PRODUCT_TYPE;

-- Are customers more likely to have higher shipping standards when they rate a product higher
SELECT S.SHIPPING_TYPE, AVG(O.RATING) AS AVG_RATING
FROM SHIPPING S
JOIN ORDERS O
ON S.ORDER_ID = O.ORDER_ID
GROUP BY S.SHIPPING_TYPE;

-- 1. Which customer spent the most for each product type
SELECT PRODUCT_TYPE, CUSTOMER_ID, TOTAL_SPENDING
FROM(
    SELECT PRODUCT_TYPE, CUSTOMER_ID, TOTAL_SPENDING,
        ROW_NUMBER() OVER (PARTITION BY PRODUCT_TYPE ORDER BY TOTAL_SPENDING DESC) AS CUST_RANK
    FROM (
        SELECT P.PRODUCT_TYPE, O.CUSTOMER_ID, SUM(O.TOTAL_PRICE) AS TOTAL_SPENDING
        FROM PRODUCT P
        JOIN ORDERS O
        ON P.PRODUCT_ID = O.PRODUCT_ID
        GROUP BY P.PRODUCT_TYPE, O.CUSTOMER_ID
    )
)
WHERE CUST_RANK = 1
ORDER BY PRODUCT_TYPE;


-- 2. What are the total sales for each product
SELECT P.PRODUCT_ID, SUM(O.TOTAL_PRICE) AS TOTAL_SPENT
FROM PRODUCT P
JOIN ORDERS O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SPENT DESC;



-- 3. Does gender influence spending habits in terms of amount spent
SELECT GENDER, AVG(O.TOTAL_PRICE) AS AVG_SPENT, SUM(O.TOTAL_PRICE) AS TOTAL_SPENT
FROM CUSTOMER C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY GENDER;


-- 4. Which ages spent the most money
SELECT AGE, SUM(O.TOTAL_PRICE) AS TOTAL_PRICE
FROM CUSTOMER C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY AGE
ORDER BY TOTAL_PRICE DESC;

-- 5. Do loyalty members spend more than non loyalty members
SELECT LOYALTY_MEMBER, AVG(TOTAL_PRICE) AS TOTAL_PRICE 
FROM ORDERS
GROUP BY LOYALTY_MEMBER;

-- 6. Which products types have the highest rating and how does it correlate with sales volume.
SELECT P.PRODUCT_TYPE, SUM(TOTAL_PRICE) AS TOTAL_SALES, AVG(O.RATING) AS AVG_RATING, COUNT(*) AS ITEMS_BOUGHT
FROM PRODUCT P
JOIN ORDERS O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_TYPE
ORDER BY TOTAL_SALES DESC;

-- 7. Does unit price affect the number of items sold.
SELECT P.PRODUCT_TYPE, P.PRODUCT_ID, P.UNIT_PRICE, SUM(O.QUANTITY) AS UNITS_SOLD
FROM PRODUCT P
JOIN ORDERS O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY PRODUCT_TYPE, P.PRODUCT_ID, P.UNIT_PRICE
ORDER BY UNITS_SOLD DESC;


-- 8. How did sales vary in terms of product type
SELECT P.PRODUCT_TYPE, SUM(O.TOTAL_PRICE) AS TOTAL_SPENT,
    AVG(TOTAL_PRICE) AS AVG_PRICE, COUNT(*) AS NUMBER_OF_ORDERS
FROM ORDERS O
JOIN PRODUCT P
ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY PRODUCT_TYPE
ORDER BY TOTAL_SPENT DESC;

-- 9. What were the most used payement methods and how much was spent
SELECT PAYMENT_METHOD, COUNT(PAYMENT_METHOD) AS METHOD_COUNT, AVG(TOTAL_PRICE), SUM(TOTAL_PRICE)
FROM ORDERS
GROUP BY PAYMENT_METHOD
ORDER BY METHOD_COUNT DESC;

-- 10. What is average rating for customers who purchased add-ons and those who didn't
-- and overall does the presence of add_ons purchased effect the sales .
SELECT ADD_ONS_PURCHASED, AVG(RATING) AS AVG_RATING, AVG(TOTAL_PRICE)
FROM (
    SELECT O.ORDER_ID, O.RATING, O.TOTAL_PRICE,
        CASE
            WHEN A.ADD_ONS_PURCHASED = 'None' THEN 'No'
            ELSE 'Yes'
        END AS ADD_ONS_PURCHASED
    FROM ORDERS O
    LEFT JOIN ADD_ONS A
    ON O.ORDER_ID = A.ORDER_ID
)
GROUP BY ADD_ONS_PURCHASED;


-- 11. Are there any peaks in sales depending on the season of the purchase date
WITH DATE_SEASON_ORDER AS (
SELECT ORDER_ID, PURCHASE_DATE, TOTAL_PRICE,
    CASE
        WHEN EXTRACT(MONTH FROM PURCHASE_DATE) IN (12,1,2) THEN 'Winter'
        WHEN EXTRACT(MONTH FROM PURCHASE_DATE) IN (3, 4, 5) THEN 'Spring'
        WHEN EXTRACT(MONTH FROM PURCHASE_DATE) IN (6, 7, 8) THEN 'Summer'
        WHEN EXTRACT(MONTH FROM PURCHASE_DATE) IN (9, 10, 11) THEN 'Fall'        
    END AS SEASON
FROM ORDERS
)
SELECT SEASON, AVG(TOTAL_PRICE) AS AVG_SPENT
FROM DATE_SEASON_ORDER
GROUP BY SEASON;

--for powerbi




--rank products by average rating
CREATE OR REPLACE VIEW PRODUCT_RATINGS AS
WITH PRODUCT_ORDERS AS (
    SELECT P.PRODUCT_TYPE, P.PRODUCT_ID, O.RATING
    FROM PRODUCT P
    JOIN ORDERS O
    ON P.PRODUCT_ID = O.PRODUCT_ID
)
SELECT PRODUCT_TYPE, PRODUCT_ID,
    RANK() OVER (ORDER BY AVG(RATING) DESC) AS PRODUCT_RANK,
    AVG(RATING) AS AVG_RATING
FROM PRODUCT_ORDERS
GROUP BY PRODUCT_TYPE, PRODUCT_ID;

--DOES GENDER INFLUENCE SPENDING HABITS IN TERMS OF MONEY SPENT
CREATE OR REPLACE VIEW GENDER_SPENDING AS
SELECT GENDER, AVG(O.TOTAL_PRICE) AS AVG_SPENT, SUM(O.TOTAL_PRICE) AS TOTAL_SPENT
FROM CUSTOMER C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY GENDER;

--DOES GENDER INFLUENCE PRODUCT TYPE
CREATE OR REPLACE VIEW GENDER_PRODUCT_TYPES AS
WITH ORDER_PRODUCT AS (
SELECT C.CUSTOMER_ID, C.GENDER, O.PRODUCT_ID
FROM CUSTOMER C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
) 
SELECT P.PRODUCT_TYPE, OP.GENDER, COUNT(P.PRODUCT_TYPE) AS P_GEND_COUNT
FROM ORDER_PRODUCT OP
JOIN PRODUCT P
ON OP.PRODUCT_ID = P.PRODUCT_ID
GROUP BY OP.GENDER, P.PRODUCT_TYPE
ORDER BY P.PRODUCT_TYPE;




--WHICH AGES SPENT THE MOST MONEY
CREATE OR REPLACE VIEW AGE_SPENDING AS
SELECT AGE, SUM(O.TOTAL_PRICE) AS TOTAL_PRICE
FROM CUSTOMER C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY AGE
ORDER BY AGE;

--calculate running total of each customer
CREATE OR REPLACE VIEW CUSTOMER_SPENDING AS
SELECT CUSTOMER_ID, PURCHASE_DATE, TOTAL_PRICE,
    SUM(TOTAL_PRICE) OVER (PARTITION BY CUSTOMER_ID ORDER BY PURCHASE_DATE) AS RUNNING_TOTAL
FROM ORDERS;

--HOW DOES UNIT PRICE AFFECT NUMBER OF UNITS SOLD
CREATE OR REPLACE VIEW PRICE_CORR_UNITS_SOLD AS
SELECT P.PRODUCT_TYPE, P.PRODUCT_ID, P.UNIT_PRICE, SUM(O.QUANTITY) AS UNITS_SOLD
FROM PRODUCT P
JOIN ORDERS O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY PRODUCT_TYPE, P.PRODUCT_ID, P.UNIT_PRICE
ORDER BY UNITS_SOLD DESC;



--are there any peaks in sales depending on the season of the purchase date
CREATE OR REPLACE VIEW SEASONAL_SALES AS
WITH DATE_SEASON_ORDER AS (
SELECT ORDER_ID, PURCHASE_DATE, TOTAL_PRICE,
    CASE
        WHEN EXTRACT(MONTH FROM PURCHASE_DATE) IN (12,1,2) THEN 'Winter'
        WHEN EXTRACT(MONTH FROM PURCHASE_DATE) IN (3, 4, 5) THEN 'Spring'
        WHEN EXTRACT(MONTH FROM PURCHASE_DATE) IN (6, 7, 8) THEN 'Summer'
        WHEN EXTRACT(MONTH FROM PURCHASE_DATE) IN (9, 10, 11) THEN 'Fall'        
    END AS SEASON
FROM ORDERS
)
SELECT SEASON, AVG(TOTAL_PRICE) AS AVG_SPENT
FROM DATE_SEASON_ORDER
GROUP BY SEASON;

CREATE OR REPLACE VIEW SEASONAL_SALES_ AS
WITH DATE_SEASON_ORDER AS (
SELECT ORDER_ID, PURCHASE_DATE, TOTAL_PRICE,
    CASE
        WHEN EXTRACT(MONTH FROM PURCHASE_DATE) IN (12,1,2) THEN 'Winter'
        WHEN EXTRACT(MONTH FROM PURCHASE_DATE) IN (3, 4, 5) THEN 'Spring'
        WHEN EXTRACT(MONTH FROM PURCHASE_DATE) IN (6, 7, 8) THEN 'Summer'
        WHEN EXTRACT(MONTH FROM PURCHASE_DATE) IN (9, 10, 11) THEN 'Fall'        
    END AS SEASON
FROM ORDERS
)
SELECT SEASON, TOTAL_PRICE
FROM DATE_SEASON_ORDER;

--TOTAL SALES BY PRODUCT
CREATE OR REPLACE VIEW TOTAAL_SPENT_BY_PRODUCT AS
SELECT P.PRODUCT_ID, SUM(O.TOTAL_PRICE) AS TOTAL_SPENT
FROM PRODUCT P
JOIN ORDERS O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SPENT DESC;

CREATE OR REPLACE VIEW SALES_PER_PRODUCT_TYPE AS
--How did sales vary in terms of product type
SELECT P.PRODUCT_TYPE, SUM(O.TOTAL_PRICE) AS TOTAL_SPENT,
    AVG(TOTAL_PRICE) AS AVG_PRICE, COUNT(*) AS NUMBER_OF_ORDERS
FROM ORDERS O
JOIN PRODUCT P
ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY PRODUCT_TYPE
ORDER BY TOTAL_SPENT DESC;

--calculate running total of all orders
CREATE OR REPLACE VIEW TOTAL_ORDERS AS
SELECT ORDER_ID, PURCHASE_DATE, TOTAL_PRICE,
    SUM(TOTAL_PRICE) OVER (ORDER BY PURCHASE_DATE, ORDER_ID) AS RUNNING_TOTAL
FROM ORDERS;